import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const poppins = Poppins ({
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	subsets: ['latin'],
 })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
	  <div className="w-full pt-36 flex flex-col items-center">
          <Link href="/" className="text-5xl font-bold">
			espressive
          </Link>
	  </div>
	  <div>
		{children}
	  </div>
	  </body>
    </html>
  )
}
